FROM golang:1.14
ADD . /server
WORKDIR /server
RUN apt-get update
RUN apt-get -y install npm
RUN npm i -g nodemon
RUN go mod download
EXPOSE 5001
CMD ["nodemon", "--exec", "go run server.go", "--signal", "SIGTERM"]
